// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) Contributors to the OpenEXR Project.

#ifndef INCLUDED_OPENEXR_CONFIG_H
#define INCLUDED_OPENEXR_CONFIG_H 1

#pragma once

#ifndef INCLUDED_OPENEXR_VERSION_H
#define OPENEXR_VERSION_MAJOR 3
#define OPENEXR_VERSION_MINOR 4
#define OPENEXR_VERSION_PATCH 13
#define OPENEXR_SOVERSION 33
#endif

#define OPENEXR_IMATH_SOVERSION 30
#define OPENEXR_IMATH_VERSION_MAJOR 3
#define OPENEXR_IMATH_VERSION_MINOR 2
#define OPENEXR_IMATH_VERSION_PATCH 2

#define OPENEXR_OPENJPH_VERSION_MAJOR 0
#define OPENEXR_OPENJPH_VERSION_MINOR 26
#define OPENEXR_OPENJPH_VERSION_PATCH 3

#define OPENEXR_IMF_INTERNAL_NAMESPACE_CUSTOM 0
#define OPENEXR_IMF_INTERNAL_NAMESPACE Imf_3_4

#define OPENEXR_IMF_NAMESPACE_CUSTOM 0
#define OPENEXR_IMF_NAMESPACE Imf

#define OPENEXR_VERSION_STRING "3.4.13"
#define OPENEXR_PACKAGE_STRING "OpenEXR 3.4.13"

#define OPENEXR_VERSION_RELEASE_TYPE ""
#define OPENEXR_VERSION_EXTRA ""

#define OPENEXR_LIB_VERSION_STRING "33.3.4.13"

#define OPENEXR_VERSION_HEX (((OPENEXR_VERSION_MAJOR) << 24) | ((OPENEXR_VERSION_MINOR) << 16) | ((OPENEXR_VERSION_PATCH) << 8))

#ifndef __has_attribute
#define __has_attribute(x) 0
#endif

#define OPENEXR_ENABLE_API_VISIBILITY

#if defined(OPENEXR_ENABLE_API_VISIBILITY) && !(defined(OPENEXR_DLL) || defined(_MSC_VER) || defined(_WIN32))
#define OPENEXR_PUBLIC_SYMBOL_ATTRIBUTE __attribute__((__visibility__("default")))
#define OPENEXR_PRIVATE_SYMBOL_ATTRIBUTE __attribute__((__visibility__("hidden")))
#if __has_attribute(__type_visibility__)
#define OPENEXR_PUBLIC_TYPE_VISIBILITY_ATTRIBUTE __attribute__((__type_visibility__("default")))
#endif
#define OPENEXR_EXPORT OPENEXR_PUBLIC_SYMBOL_ATTRIBUTE
#define OPENEXR_HIDDEN OPENEXR_PRIVATE_SYMBOL_ATTRIBUTE
#define OPENEXR_EXPORT_TYPE OPENEXR_EXPORT
#define OPENEXR_EXPORT_EXTERN_TEMPLATE OPENEXR_EXPORT
#ifdef OPENEXR_PUBLIC_TYPE_VISIBILITY_ATTRIBUTE
#define OPENEXR_EXPORT_ENUM OPENEXR_PUBLIC_TYPE_VISIBILITY_ATTRIBUTE
#define OPENEXR_EXPORT_TEMPLATE_TYPE OPENEXR_PUBLIC_TYPE_VISIBILITY_ATTRIBUTE
#define OPENEXR_EXPORT_TEMPLATE_INSTANCE OPENEXR_EXPORT
#else
#define OPENEXR_EXPORT_ENUM
#define OPENEXR_EXPORT_TEMPLATE_TYPE OPENEXR_EXPORT
#define OPENEXR_EXPORT_TEMPLATE_INSTANCE
#endif
#else
#define OPENEXR_EXPORT
#define OPENEXR_HIDDEN
#define OPENEXR_EXPORT_TYPE
#define OPENEXR_EXPORT_EXTERN_TEMPLATE
#define OPENEXR_EXPORT_ENUM
#define OPENEXR_EXPORT_TEMPLATE_TYPE
#define OPENEXR_EXPORT_TEMPLATE_INSTANCE
#endif

#if defined(__cplusplus) && (__cplusplus >= 201402L)
#define OPENEXR_DEPRECATED(msg) [[deprecated(msg)]]
#endif

#ifndef OPENEXR_DEPRECATED
#ifdef _MSC_VER
#define OPENEXR_DEPRECATED(msg) __declspec(deprecated(msg))
#else
#define OPENEXR_DEPRECATED(msg) __attribute__((deprecated(msg)))
#endif
#endif

#endif
