#ifndef OPENIMAGEIO_BUILDOPTS_H
#define OPENIMAGEIO_BUILDOPTS_H

#define OIIO_DEFAULT_PLUGIN_SEARCHPATH ""
#define OIIO_ALL_BUILD_DEPS_FOUND "OpenEXR;Imath;OpenColorIO;ZLIB;TIFF;JPEG;fmt;robinmap"

#endif
