"""Generate the pinned OCIO source overlay that owns its LUT format registry.

Upstream remains byte-identical. Only registry lifetime and the relocated
private header include differ in the compiled overlay.
"""
from pathlib import Path
import argparse
import hashlib

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'third_party/opencolorio/opencolorio_src'

def generate():
    original = (SOURCE / 'upstream/src/OpenColorIO/transforms/FileTransform.cpp').read_text(encoding='utf-8')
    old = '''    if(!g_formatRegistry)
    {
        g_formatRegistry = new FormatRegistry();
    }
'''
    new = '''    // The static U++ build must release the registry before its heap audit.
    // This deleter is defined in member scope so the private destructor stays
    // private. Each raw format is registered once and shared by lookup maps.
    static const auto destroy = [](FormatRegistry * registry) {
        for(int i = 0; i < registry->getNumRawFormats(); ++i)
            delete registry->getRawFormatByIndex(i);
        delete registry;
        g_formatRegistry = nullptr;
    };
    static const std::unique_ptr<FormatRegistry, decltype(destroy)> owner(
        new FormatRegistry(), destroy);
    g_formatRegistry = owner.get();
'''
    if original.count(old) != 1:
        raise SystemExit('Pinned OCIO registry source changed; review the lifetime overlay')
    output = original.replace(old, new).replace('#include "FileTransform.h"', '#include "transforms/FileTransform.h"')
    output = '\n'.join(line.rstrip() for line in output.splitlines()) + '\n'
    return '// Generated by tools/generate_ocio_file_transform.py; do not edit.\n' + output

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    result = generate()
    target = SOURCE / 'generated_include/FileTransform.cpp'
    if args.check:
        if target.read_text(encoding='utf-8') != result:
            raise SystemExit('OCIO FileTransform overlay is out of date')
    else:
        target.write_text(result, encoding='utf-8', newline='\n')
    print('OCIO FileTransform overlay SHA256:', hashlib.sha256(result.encode()).hexdigest())

if __name__ == '__main__':
    main()
